"""empty message

Revision ID: 737aeab890e6
Revises: 6f1474997544
Create Date: 2025-09-23 18:24:24.525688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737aeab890e6'
down_revision = '6f1474997544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terreno', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('terreno')

    op.drop_table('people')
    op.drop_table('favorites')
    # ### end Alembic commands ###
